# Generated by Django 3.1.7 on 2021-05-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210503_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cuisine',
            field=models.CharField(default='Indian', max_length=150),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='radio',
            field=models.CharField(default='Veg', max_length=150),
        ),
    ]
