# Generated by Django 3.1.7 on 2021-05-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210503_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
